services:
  postfix:
    build: .
    image: ghcr.io/gabez143/postfix-relay:latest
    ports:
      - "587:587"
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./postfix/main.cf:/etc/postfix/main.cf:ro
      - ./postfix/master.cf:/etc/postfix/master.cf:ro
      - ./sasl:/etc/sasl2:ro
      - ./secrets/sasldb2:/etc/sasldb2:ro
      - ./secrets/certs:/etc/ssl/postfix:ro
      - ./secrets/virtual:/etc/postfix/virtual:ro
    
    secrets:
      - sasl_passwd

secrets:
  sasl_passwd:
    file: ./secrets/sasl_passwd
