name: build-and-push

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      OWNER_LC: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Force lowercase owner
        run: echo "OWNER_LC=${OWNER_LC,,}" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC) }}/postfix-relay:latest
            ghcr.io/${{ env.OWNER_LC) }}/postfix-relay:${{ github.sha }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
